---
- name: Install Rancher
  hosts: localhost
  gather_facts: false
  vars:
    ansible_user: kevin
    public_nic: gdale-rancher-vm1-publicip1
    rsg: rsg-rancher
  tasks:
    - name: Get public ip info by name
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: "{{ rsg }}"
        name: "{{ public_nic }}"
        cert_validation_mode: validate
        client_id: "{{ lookup('ansible.builtin.env', 'AZ_CLIENT_ID') }}"
        subscription_id: "{{ lookup('ansible.builtin.env', 'AZ_SUB_ID') }}"
        tenant: "{{ lookup('ansible.builtin.env', 'AZ_TENANT_ID') }}"
        secret: "{{ lookup('ansible.builtin.env', 'AZ_SECRET') }}"
      register: az_vm_info

    - name: Add host
      ansible.builtin.add_host:
        name: "{{ az_vm_info.publicipaddresses[0].ip_address }}"

    - name: Gather VM facts
      ansible.builtin.setup:
      delegate_to: "{{ az_vm_info.publicipaddresses[0].ip_address }}"
    
    - name: Configure Rancher
      delegate_to: "{{ az_vm_info.publicipaddresses[0].ip_address }}"
      become: true
      become_user: root
      block:
        - name: Download Helm script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /usr/local/bin/get_helm.sh
            mode: '0700'
        
        - name: Install Helm
          ansible.builtin.command: /usr/local/bin/get_helm.sh
          register: helm_install
        
        - name: Add Rancher chart repo
          kubernetes.core.helm_repository:
            name: stable
            repo_url: "https://releases.rancher.com/server-charts/latest"

        - name: Download pip script
          ansible.builtin.get_url:
            url: https://bootstrap.pypa.io/get-pip.py
            dest: /usr/local/bin/get-pip.py
            mode: '0700'
        
        - name: Install pip
          ansible.builtin.command: python3 /usr/local/bin/get-pip.py
          register: pip_install

        - name: Install Python packages
          ansible.builtin.pip:
            name: 
              - kubernetes
              - jsonpatch
              - PyYAML

        - name: Create root namespace
          kubernetes.core.k8s:
            name: cattle-system
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            api_version: v1
            kind: Namespace
            state: present
        
        - name: Apply cert-manager config
          kubernetes.core.k8s:
            apply: true
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            api_version: v1
            src: "https://github.com/cert-manager/cert-manager/releases/download/v1.13.4/cert-manager.crds.yaml"
            state: present
        
        - name: Add cert-manager chart repo
          kubernetes.core.helm_repository:
            name: jetstack
            repo_url: "https://charts.jetstack.io"
        
        - name: Install cert-manager
          kubernetes.core.helm:
            name: cert-manager
            chart_ref: jetstack/cert-manager
            create_namespace: true
            release_name: cert-manager
            namespace: cert-manager
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            state: present
            update_repo_cache: true
        
        - name: Install Rancher
          kubernetes.core.helm:
            name: rancher
            chart_ref: rancher-latest/rancher
            release_name: rancher
            namespace: cattle-system
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            state: present
            values:
              hostname: "{{ az_vm_info.publicipaddresses[0].ip_address }}.greendale.io"
              replicas: 1
              bootstrapPassword: "{{ lookup('ansible.builtin.env', 'RANCHER_ADMIN') }}"