apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  default.server: |
    rancher.delaneyhq.com {
        hosts {
              192.168.50.101 rancher.delaneyhq.com
              fallthrough
        }
    }