name: Ansible - Install k3s

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  GDALE_PRIVATE_KEY: ${{ secrets.GDALE_PRIVATE_KEY }}
jobs:
  manage_vm:
    name: Ansible - Install k3s
    strategy:
      matrix:
         folder: [k3s]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Check runner
        run: sudo apt-get update -y

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install ansible
        run: pip3 install ansible-core
      - run: mkdir ~/.ssh && touch ~/.ssh/gdale-rancher-vm1
      - name: Add private key
        run: echo $GDALE_PRIVATE_KEY > ~/.ssh/gdale-rancher-vm1
      - name: Check ansible version
        run: ansible --version
      - name: Install Azure pre-req list
        run: pip3 install -r /opt/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible_collections/azure/azcollection/requirements-azure.txt
      - name: Install ansible collections
        run: ansible-galaxy collection install azure.azcollection
      # - name: Run playbook
      #   working-directory: k3s
      #   run: ansible-playbook install_k3s.yml --private-key ~/.ssh/gdale-rancher-vm1