name: Ansible - Install k3s

on:
  workflow_dispatch:
  push:
    branches:
      - kd-ansible-init

jobs:
  manage_vm:
    name: Ansible - Install k3s
    strategy:
      matrix:
         folder: [k3s]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Check runner
        run: sudo apt-get update -y

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'